# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - requirements: requirements.txt

sphinx:
  configuration: source_zh/conf.py
  fail_on_warning: false

formats:
  - pdf
  - epub


